FROM nvidia/cuda:12.6.3-cudnn-devel-ubuntu22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y --no-install-recommends \
    build-essential \
    git \
    libssl-dev \
    ca-certificates \
    libxmu-dev \
    libxi-dev \
    libgl-dev \
    libosmesa-dev \
    liblog4cplus-dev \
    librdmacm-dev \
    libibverbs-dev \
    libgtest-dev \
    liblz4-dev \
    cmake \
    && rm -rf /var/lib/apt/lists/*

# Build MsQuic once
RUN git clone --recurse-submodules https://github.com/microsoft/msquic.git && \
    cd msquic && \
    cmake -B build -DCMAKE_BUILD_TYPE=Release && \
    cmake --build build && \
    cmake --install build

RUN echo "/usr/local/lib" > /etc/ld.so.conf.d/msquic.conf && ldconfig
RUN ldconfig -p | grep msquic || true