FROM gvirtus_dependencies:cuda12.6

ENV GVIRTUS_HOME=/opt/GVirtuS

COPY ./src/ ${GVIRTUS_HOME}/src/
COPY ./include/ ${GVIRTUS_HOME}/include/
COPY ./etc/ ${GVIRTUS_HOME}/etc/
COPY ./cmake/ ${GVIRTUS_HOME}/cmake/
COPY ./lib/ ${GVIRTUS_HOME}/lib/
COPY ./plugins/ ${GVIRTUS_HOME}/plugins/
COPY ./tests/ ${GVIRTUS_HOME}/tests/
COPY ./CMakeLists.txt ${GVIRTUS_HOME}/CMakeLists.txt