FROM gvirtus:cuda12.6 AS final

ENV LD_LIBRARY_PATH=${GVIRTUS_HOME}/lib:${GVIRTUS_HOME}/lib/frontend:${LD_LIBRARY_PATH}

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 \
    python3-pip \
    python-is-python3 \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --no-cache-dir \
    torch==2.8.0+cu126 \
    torchvision \
    --index-url https://download.pytorch.org/whl/cu126

WORKDIR /opt/GVirtuS
